### PR TITLE
Added new functions

### PR DESCRIPTION
**Pull request by kevinholtkamp**
I added Get-RecycledItems, changed Restore-Item to use Get-RecycledItems to not have duplicate code.
Added Invoke-Elevated which runs a given ScriptBlock in an elevated powershell.
Added Read-ArrayInput to read any number of inputs from the user.

Also added proper commentary to all the above functions.

I made lots of small commits, so please squash when merging

### CODE REVIEW

**Comment by bdukes** [comment]
I've pushed the `Invoke-Elevated` change.

At the moment I'm not sure that the `Read-ArrayInput` function fits great within my `Read-Choice` module.

I haven't had a change to review the `Recycle` changes yet. Did you change the implementation of `Restore-Item`?

Thanks, I appreciate your contributions!

**Comment by kevinholtkamp** [comment]
Changes to the interface of `Restore-Item`:
- Removed Position from parameter `-Overwrite` because positional switch parameters don't make sense
- Moved up positional parameters by 1
- Renamed parameter `-SelectionCriteria` to `-SortingCriteria` since it fits better
- Added parameter `-ComObject` so you can pipe `Get-RecycledItems` into it
- Returns the `-OriginalPath` parameter now

I also moved some logic from `Restore-Item` into `Get-RecycledItems` and added new logic for passing `-ComObject`

You can take your time reviewing this, there are probably some optimizations you could do.

However I would like to know wether you want to add `Read-ArrayInput` now though, as I would add it to my own module for personal use if not.

**Comment by bdukes** [comment]
I've published [version 1.5.0 of the Recycle module](https://www.powershellgallery.com/packages/Recycle/1.5.0) with `Restore-RecycledItem` and `Get-RecycledItem` cmdlets, thanks!

**Comment by kevinholtkamp** [comment]
Thank you!

**Pull request closed without merging**
